################################# Default configuration ###################
baseURL = ""
title = "sys-don"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "techdono" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Contact Information
mobile = "9901939100, 9686081890, 9845094630"
email = "sashreek123@hotmail.com"
location = "Bengaluru, Karnataka, India"
# contact form action
contact_form_action = "https://formsubmit.co/sashreek123@hotmail.com" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "12.978129"
map_longitude = "77.572886"
map_marker = "images/marker.png" 

  
############################# social site ########################

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/sashreek-shankar-b504041aa/"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/Sashreek11"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/sashreek1/"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "© Sashreek Shankar 2020 · Made with [GitHub](), [Netlify](https://www.netlify.com/) and [Themefisher's](https://themefisher.com) airspace theme for [Hugo](https://gohugo.io/)"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About Us"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Gallery"
URL = "project"
weight = 3

#[[Languages.en.menu.main]]
#name = "Credits"
#URL = "service"
#weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Gallery"
URL = "project"
weight = 2

#[[Languages.en.menu.footer]]
#name = "Credits"
#URL = "service"
#weight = 3

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6

